SELECT

    /*
        Product templates contain shared product master data across variants,
        including category, UoM, purchasing/sales flags, and costing attributes.
    */

    /* IDS */
    id as product_template_id,
    categ_id as product_category_id,
    uom_id,
    uom_po_id as purchase_uom_id,
    company_id,
    create_uid as created_by_user_id,
    write_uid as updated_by_user_id,
    origin_country_id,
    expert_id,
    scm_id,
    country_of_origin,

    /* TIMESTAMPS */
    create_date as created_at,
    write_date as updated_at,

    /* DATES */
    expected_eol,

    /* DIMENSIONS */
    name as product_name_raw,
    coalesce(json_value(name, '$.en_GB'), json_value(name, '$.en_US')) as product_name,
    json_value(name, '$.en_US') as product_name_en_us,
    sequence,
    description as description_raw,
    json_value(description, '$.en_GB') as description,
    description_purchase as purchase_description_raw,
    json_value(description_purchase, '$.en_GB') as purchase_description,
    description_sale as sale_description_raw,
    json_value(description_sale, '$.en_GB') as sale_description,
    type as product_type,
    sale_ok as is_saleable,
    purchase_ok as is_purchasable,
    active as is_active,
    color,
    default_code as product_code,
    can_image_1024_be_zoomed as can_image_be_zoomed,
    has_configurable_attributes,
    service_type,
    sale_line_warn,
    sale_line_warn_msg,
    expense_policy,
    invoice_policy,
    tracking,
    description_picking as picking_description_raw,
    json_value(description_picking, '$.en_GB') as picking_description,
    description_pickingout as picking_out_description_raw,
    json_value(description_pickingout, '$.en_GB') as picking_out_description,
    description_pickingin as picking_in_description_raw,
    json_value(description_pickingin, '$.en_GB') as picking_in_description,
    hs_code,
    state as product_state,
    storage as storage_method,
    purchase_method,
    purchase_line_warn,
    purchase_line_warn_msg,
    with_revision as has_revision,
    pending_modification as has_pending_modification,
    product_url,
    new_internal_code,
    landed_cost_ok as is_landed_cost_enabled,
    split_method_landed_cost,
    commercial_invoice_description,
    wp_master as is_wp_master,
    allow_negative_stock as allows_negative_stock,
    x_studio_eccn_number,
    x_studio_storage_box,
    internal_logistic_batch as uses_internal_logistic_batch,
    internal_logistic_batch_after_manufacturing as uses_internal_logistic_batch_after_manufacturing,
    x_studio_sellable_product as is_studio_sellable_product,
    x_studio_procurable_product as is_studio_procurable_product,
    x_studio_x_studio_procurable_product as is_studio_procurable_product_duplicate,
    is_lithium_batteries,
    battery_type,
    add_product_to_commercial_invoice as should_add_product_to_commercial_invoice,
    part_number,
    pdm_link_model,
    pdm_link_drawing,
    pdm_status,
    pdm_attachment,
    pcba_revision,
    x_studio_char_field_a_gus3,
    specification as specification_raw,
    definition as definition_raw,
    reason as reason_raw,
    product_properties as product_properties_raw,
    create_repair as should_create_repair,
    last_direct_labour as last_direct_labour_raw,
    responsible_id as responsible_property_raw,
    internal_logistics as internal_logistics_raw,
    report_internal_logistics as report_internal_logistics_raw,
    direct_labour as direct_labour_raw,
    last_indirect_production as last_indirect_production_raw,
    last_internal_logistics as last_internal_logistics_raw,
    last_type_specific_tooling_ext as last_type_specific_tooling_ext_raw,
    report_landing_cost as report_landing_cost_raw,
    property_stock_production as stock_production_property_raw,
    landing_cost as landing_cost_raw,
    type_specific_tooling_ext as type_specific_tooling_ext_raw,
    last_landing_cost as last_landing_cost_raw,
    hs_code_id as hs_code_property_raw,
    service_to_purchase as service_to_purchase_raw,
    indirect_production as indirect_production_raw,
    property_stock_inventory as stock_inventory_property_raw,
    report_direct_labour as report_direct_labour_raw,
    report_type_specific_tooling_ext as report_type_specific_tooling_ext_raw,
    report_indirect_production as report_indirect_production_raw,
    is_favorite,
    service_tracking,
    property_account_income_id as account_income_property_raw,
    property_account_expense_id as account_expense_property_raw,
    is_storable,
    lot_valuated as is_lot_valuated,
    property_account_creditor_price_difference as account_creditor_price_difference_property_raw,
    type_specific_tooling_int as type_specific_tooling_int_raw,
    last_type_specific_tooling_int as last_type_specific_tooling_int_raw,
    report_type_specific_tooling_int as report_type_specific_tooling_int_raw,
    it_cost as it_cost_raw,
    last_it_cost as last_it_cost_raw,
    report_it_cost as report_it_cost_raw,
    machine_cost as machine_cost_raw,
    last_machine_cost as last_machine_cost_raw,
    report_machine_cost as report_machine_cost_raw,

    /* METRICS */
    list_price,
    volume,
    weight,
    sale_delay,
    length,
    width,
    height,
    net_weight,
    x_studio_monetary_field_wo_o25,
    x_studio_foc_price,
    internal_logistic_batch_size,
    internal_logistic_batch_size_after_manufacturing,

FROM {{ source('odoo', 'product_template') }}

-- Filter out CEE (company_id=8) per project policy: CEE is the outdated Wingtra - CEE entity.
-- Multi-company shared templates (company_id IS NULL) and the single Corp template
-- (company_id=9, an Odoo "Discount" service stub) are kept.
WHERE _dlt_deleted_at IS NULL
  AND (company_id IS NULL OR company_id != 8)
